
export const levelData = [
  {
    level: 1,
    enemies: 1,
    objective: "kill the alien",
    missionAddress: "B6bVVUsGnkCD4sJDxSaAJfzrzB6ucqEQGtd48BbL5g8o",
    timed: false,
    duration: "0",
    rewardXp: "5",
    rewardGold: "0",
  },
  {
    level: 2,
    enemies: 3,
    objective: "kill 2 aliens in 60 seconds",
    missionAddress: "Bw2iCEmy4tFHo3e1M1WamatAnUVHYGM9US1doPq5wBiS",
    timed: true,
    duration: "60",
    rewardXp: "5",
    rewardGold: "0",
  },
  {
    level: 3,
    enemies: 5,
    objective: "clear the area of 5 aliens",
    missionAddress: "F1spwZkXbg5bfnGvFJdng5EYWoyVoCewQ39BP5fM3mzR",
    timed: false,
    duration: "0",
    rewardXp: "7",
    rewardGold: "0",
  },
  {
    level: 4,
    enemies: 5,
    objective: "defeat 4 aliens in 45 seconds",
    missionAddress: "5GVEDDanm3zkK8Q2aiL9LzEGGyt8TtLeec3gkhwXb1kp",
    timed: true,
    duration: "45",
    rewardXp: "7",
    rewardGold: "0",
  },
  {
    level: 5,
    enemies: 5,
    objective: "eliminate all aliens",
    missionAddress: "9fJnnit8FvEo541xerTr1V99WVahf1wE8EEpgs6gP5FZ",
    timed: false,
    duration: "0",
    rewardXp: "10",
    rewardGold: "0",
  },
  {
    level: 6,
    enemies: 4,
    objective: "kill 3 aliens in 40 seconds",
    missionAddress: "Gbx9bnHZWbqeewN96yVJDh3q3s6Qkg2u3RpXzijY11H1",
    timed: true,
    duration: "40",
    rewardXp: "10",
    rewardGold: "0",
  },
  {
    level: 7,
    enemies: 6,
    objective: "clear the zone",
    missionAddress: "9ojsYq5JhAZc8hZ4nkpXDftHjKLfY4jEYrMQ1RsXTyj7",
    timed: false,
    duration: "0",
    rewardXp: "12",
    rewardGold: "0",
  },
  {
    level: 8,
    enemies: 8,
    objective: "destroy alien in 80 seconds",
    missionAddress: "6gRydSTsQ6Ddb55mRMKyuf3dpkgG3TeemGxzVKKCQwh6",
    timed: true,
    duration: "80",
    rewardXp: "15",
    rewardGold: "0",
  },
  {
    level: 9,
    enemies: 7,
    objective: "defend the outpost",
    missionAddress: "BUkPctKwjssjJwhkz8h2Lk2vAY3KBsHVWYs9636tR1ZJ",
    timed: false,
    duration: "0",
    rewardXp: "15",
    rewardGold: "0",
  },
  {
    level: 10,
    enemies: 10,
    objective: "wipe out the alien in 90 seconds",
    missionAddress: "7kZhqnXTreQJM9q9dk7QgbWko7WLScUnQanM6Z9ZFzSt",
    timed: true,
    duration: "90",
    rewardXp: "20",
    rewardGold: "5",
  },
];

